---
title: "Publications"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


* C. Gauchy, J. Stenger, R. Sueur and B. Iooss. \
  An information geometry approach for robustness analysis in uncertainty quantification of computer codes. \
  *Technometrics* 64(1):80-91, 2022\
  [HAL](https://hal.archives-ouvertes.fr/hal-02425477)
  [link](https://www.tandfonline.com/doi/full/10.1080/00401706.2021.1905072)
  
* C. Gauchy, C. Feau, J. Garnier \
  Importance sampling based active learning for parametric seismic fragility curve estimation. \
  Preprint \
  [Arxiv](https://arxiv.org/abs/2109.04323)

* C. Gauchy, C. Feau, J. Garnier \
  Estimation of seismic fragility curves by sequential design of experiments. \
  Conference preprint   
  [HAL](https://hal.archives-ouvertes.fr/hal-03588974)
  
* C. Gauchy, C. Feau, J. Garnier \
  Uncertainty quantification and global sensitivity analysis of seismic fragility curves using kriging. \
  *International Journal of Uncertainty Quantification* 14(4):39-63, 2024\
  [Arxiv](https://arxiv.org/abs/2210.06266)
  [link](https://dl.begellhouse.com/journals/52034eb04b657aea,20894a8061d92d69,260586e7059072e4.html)

* A. Van Biesbroeck, C. Gauchy, C. Feau, J. Garnier \ 
  Reference prior for Bayesian estimation of seismic fragility curves. \
  *Probabilistic Engineering Mechanics* 2024 \
  [Arxiv](https://arxiv.org/abs/2302.06935)
  [link](https://www.sciencedirect.com/science/article/pii/S0266892024000444)
